### 자료형 ndarray

In [1]:
import numpy as np

a = np.ndarray(shape=(2, 2), dtype=int)
a

array([[0, 0],
       [0, 0]])

In [2]:
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [3]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [4]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [5]:
a.data

In [6]:
import numpy as np

np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [7]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [8]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [9]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [11]:
lang = np.array(['파이썬', '자바', '씨'], dtype='str')
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

### 내장함수 arange()와 linspace()

In [12]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


### 배열 연산 

In [1]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [2]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [3]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = np.full_like(a, [1, 2, 3])

In [5]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [7]:
b = np.arange(0.5, 4, 1)

In [8]:
a += b # 에러

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [10]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [11]:
a = np.full((2, 3), [1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [13]:
b @ a

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [14]:
a @ b

array([[12,  6],
       [12,  6]])

In [15]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [16]:
print(np.matmul(a, b))

[[12  6]
 [12  6]]


In [17]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [18]:
a.sum()

np.int64(46)

In [ ]:
a.sum(axis=0) # 열 합 배열 **시험 출제 에상**

array([16, 30])

In [ ]:
a.sum(axis=1) # 행 합 배열 **시험 출제 에상**

array([30, 13,  3])

In [21]:
# cumsum
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [23]:
a.cumsum() # 일차원으로 펼쳐서 계산

array([ 3,  8, 16, 17, 19, 22])

In [24]:
a.cumsum(axis=0) # 열 누적 합 배열

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [25]:
a.cumsum(axis=1) # 행 누적 합 배열

array([[ 3,  8, 16],
       [ 1,  3,  6]])

#### 범용 함수

In [26]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [27]:
b = np.full_like(a, 2)

In [28]:
b

array([2, 2, 2])

In [29]:
np.add(a, b)

array([ 3,  6, 11])

In [30]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [31]:
np.power(a, b)

array([ 1, 16, 81])

### 배열 슬라이싱과 형태 수정

In [32]:
import numpy as np

a = np.power(np.arange(10), 2)

In [33]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
print(a[3])
print(a[-2])

9
64


In [35]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [36]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [37]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [38]:
a[::-2]

array([81, 49, 25,  9,  1])

In [39]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [40]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

#### 2차원 배열의 첨자와 슬라이싱

In [41]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [43]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [44]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [45]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [46]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [47]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [48]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [49]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [50]:
a = np.arange(30).reshape(5, 6)

In [51]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [52]:
a[2, 4]

np.int64(16)

In [53]:
a[2][4]

np.int64(16)

In [54]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [55]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a[:-1, :-1] # 마지막 행과 열을 제외한 배열 반환

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
a[1] # axis=0, 첨자 1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [60]:
a[:, 1, 1]

array([ 5, 17])

In [61]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [62]:
a[..., 1] 

array([[ 1,  5,  9],
       [13, 17, 21]])

In [63]:
a[1, ..., 1]

array([13, 17, 21])

In [64]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
a = np.arange(1, 7).reshape(2, 3)

In [68]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 브로드캐스팅

In [71]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a+b

array([11, 11, 11])

In [72]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])

a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [73]:
X = np.arange(1, 10).reshape(3, 3)
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [76]:
X * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [77]:
X + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [78]:
y = np.arange(3, 10, 3).reshape(3, 1)

In [79]:
y

array([[3],
       [6],
       [9]])

In [80]:
np.set_printoptions(precision=2)

In [81]:
X / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [82]:
X - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [83]:
X = np.arange(1, 4)
X

array([1, 2, 3])

In [84]:
y = np.arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [85]:
X * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [86]:
X / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [87]:
X = np.arange(0, 10, 3).reshape(4, 1)

In [88]:
y = np.arange(1, 3)

In [89]:
X * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [90]:
X + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

#### 상수 np.newaxis 활용한 배열 차원 확장

In [91]:
X = np.array([0, 10, 20, 30])
X

array([ 0, 10, 20, 30])

In [92]:
np.newaxis is None

True

In [93]:
# 차수를 증강
a = X[None, :]
a

array([[ 0, 10, 20, 30]])

In [94]:
a = X[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [95]:
a = X[:, np.newaxis]

In [96]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [97]:
b = np.array([1, 2, 3])
a = X[:, np.newaxis]

a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [98]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### 고급 색인

In [99]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [101]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [102]:
# 예를들어
x = np.array([1, 3, 5, 7, 9])
x[ [0, 1, 3]]

array([1, 3, 7])

In [103]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [104]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [105]:
x[0, 1]

np.int64(1)

In [106]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
print(x[ [0, 1] ]) # 0행, 1행 출력
print(x[0, 1]) # 0행, 1열 출력
print(x[ [0, 1], [1, 2] ]) # 0행의 1열과 1행의 2열을 출력

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
1
[ 1 10]


In [112]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])