### 자료형 ndarray

In [7]:
import numpy as np

a = np.ndarray(shape=(2, 2), dtype=int)
a

array([[0, 0],
       [0, 0]])

In [8]:
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [9]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [10]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [11]:
a.data

In [12]:
import numpy as np

# np.array(1, 2, 3)

In [13]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [14]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [15]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [16]:
lang = np.array(['파이썬', '자바', '씨'], dtype='str')
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [17]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [18]:
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


### 배열 연산 

In [19]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [20]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [21]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

#### 함수 linspace

In [27]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [28]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [29]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [30]:
print( (3-2) / 50)

0.02


In [31]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [32]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [22]:
b = np.full_like(a, [1, 2, 3])

내장함수 zeros(), ones, empty()

In [33]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [37]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [38]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [43]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
np.eye(3, 4, 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.eye(3, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [46]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [47]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [48]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [49]:
np.empty((4))

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323])

In [50]:
np.empty((2, 2))

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [51]:
np.empty([2, 3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [23]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [24]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [25]:
b = np.arange(0.5, 4, 1)

In [26]:
a += b # 에러

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [ ]:
a = np.full((2, 3), [1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [ ]:
b @ a

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [ ]:
a @ b

array([[12,  6],
       [12,  6]])

In [ ]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [ ]:
print(np.matmul(a, b))

[[12  6]
 [12  6]]


In [ ]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum()

np.int64(46)

In [ ]:
a.sum(axis=0) # 열 합 배열 **시험 출제 에상**

array([16, 30])

In [ ]:
a.sum(axis=1) # 행 합 배열 **시험 출제 에상**

array([30, 13,  3])

In [ ]:
# cumsum
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
a.cumsum() # 일차원으로 펼쳐서 계산

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
a.cumsum(axis=0) # 열 누적 합 배열

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [ ]:
a.cumsum(axis=1) # 행 누적 합 배열

array([[ 3,  8, 16],
       [ 1,  3,  6]])

#### 범용 함수

In [ ]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [ ]:
b = np.full_like(a, 2)

In [ ]:
b

array([2, 2, 2])

In [ ]:
np.add(a, b)

array([ 3,  6, 11])

In [ ]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [ ]:
np.power(a, b)

array([ 1, 16, 81])

### 배열 슬라이싱과 형태 수정

In [ ]:
import numpy as np

a = np.power(np.arange(10), 2)

In [ ]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[::-2]

array([81, 49, 25,  9,  1])

In [ ]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

#### 2차원 배열의 첨자와 슬라이싱

In [ ]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [ ]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [ ]:
a = np.arange(30).reshape(5, 6)

In [ ]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
a[2, 4]

np.int64(16)

In [ ]:
a[2][4]

np.int64(16)

In [ ]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [ ]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a[:-1, :-1] # 마지막 행과 열을 제외한 배열 반환

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1] # axis=0, 첨자 1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:, 1, 1]

array([ 5, 17])

In [ ]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[..., 1] 

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[1, ..., 1]

array([13, 17, 21])

In [ ]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a = np.arange(1, 7).reshape(2, 3)

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 브로드캐스팅

In [ ]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a+b

array([11, 11, 11])

In [ ]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])

a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
X = np.arange(1, 10).reshape(3, 3)
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [ ]:
X * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [ ]:
X + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
y = np.arange(3, 10, 3).reshape(3, 1)

In [ ]:
y

array([[3],
       [6],
       [9]])

In [ ]:
np.set_printoptions(precision=2)

In [ ]:
X / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [ ]:
X - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [ ]:
X = np.arange(1, 4)
X

array([1, 2, 3])

In [ ]:
y = np.arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [ ]:
X * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
X / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [ ]:
X = np.arange(0, 10, 3).reshape(4, 1)

In [ ]:
y = np.arange(1, 3)

In [ ]:
X * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [ ]:
X + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

#### 상수 np.newaxis 활용한 배열 차원 확장

In [ ]:
X = np.array([0, 10, 20, 30])
X

array([ 0, 10, 20, 30])

In [ ]:
np.newaxis is None

True

In [ ]:
# 차수를 증강
a = X[None, :]
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = X[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = X[:, np.newaxis]

In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b = np.array([1, 2, 3])
a = X[:, np.newaxis]

a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### 고급 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [ ]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [ ]:
# 예를들어
x = np.array([1, 3, 5, 7, 9])
x[ [0, 1, 3]]

array([1, 3, 7])

In [ ]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
print(x[ [0, 1] ]) # 0행, 1행 출력
print(x[0, 1]) # 0행, 1열 출력
print(x[ [0, 1], [1, 2] ]) # 0행의 1열과 1행의 2열을 출력

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
1
[ 1 10]


In [ ]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])